name: Deployment Exercise 1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install java
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'maven'
      - name: Install Dependencies
        run: mvn clean install
      - name: Test Code
        run: mvn test
      - name: Deploy to Server
        run: echo "Deploying to server..."