name: Deployment Exercise 2
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'maven'
      - name: install Dependencies
        run: mvn clean install
      - name: Test Code
        run: mvn test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'maven'
      - name: install Dependencies
        run: mvn clean install
      - name: Deploy to Server
        run: echo "Deploying to server... Exercise 2"